.\"-*- nroff -*-
.TH IMMV "1" "2009-08-18" "immv -Interactive Multi MoVe-" "User Commands"
.SH NAME
immv \- manual page for immv \-Interactive Multi MoVe\-

.SH SYNOPSIS
.B immv
.RI [\| options \|]
.RI FILES

.SH DESCRIPTION
This program allows renaming of multiple files at once by 
providing an editor with the names of the given files. 
The editor used is the one specified in the environment variable
.B $EDITOR.
If this environment variable is empty, 
.B sensible-editor
is used.
.PP
The filenames displayed in the editor are just the base filenames
without the path, since the path can't be altered.
It is possible to edit the names of files in different directories
at once.
.PP
If the target name of a file already exists, this file is skipped 
(unless the
.B --overwrite
or
.B --interactive
option is given).

.SH OPTIONS
.TP
.B \-\-version
show program's version number and exit
.TP
.B \-h, \-\-help
show this help message and exit
.TP
.B \-a, \-\-ask
ask for confirmation before doing anything
.TP
.B \-q, \-\-quiet
don't output anything, except error messages
.TP
.B \-o, \-\-overwrite
overwrite existing files
.TP
.B \-i, \-\-interactive
ask for confirmation before overwriting existing files

.SH "EXIT STATUS"
.TP
.B 0
successfully completed
.TP
.B 1
aborted before doing anything
.TP
.B 2
failure while processing


.SH ENVIRONMENT
.TP
.B EDITOR
If 
.RB $ EDITOR
is set, it will be used for editing
the file names, otherwise 
.RB sensible-editor
is used.

.SH "SEE ALSO"
.BR mmv (1),
.BR rename (1)

