Document: immv
Title: Debian immv Manual
Author: <insert document author here>
Abstract: This manual describes what immv is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/immv/immv.sgml.gz

Format: postscript
Files: /usr/share/doc/immv/immv.ps.gz

Format: text
Files: /usr/share/doc/immv/immv.text.gz

Format: HTML
Index: /usr/share/doc/immv/html/index.html
Files: /usr/share/doc/immv/html/*.html


